# Generated by Django 4.2.11 on 2026-04-22 18:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AISuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rule_triggered', models.CharField(max_length=100)),
                ('severity', models.CharField(choices=[('critical', 'Critical'), ('warning', 'Warning'), ('info', 'Info'), ('positive', 'Positive')], default='info', max_length=20)),
                ('suggestion_text', models.TextField()),
                ('confidence_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_suggestions', to='tasks.task')),
            ],
            options={
                'ordering': ['-generated_at'],
                'indexes': [models.Index(fields=['task'], name='ai_engine_a_task_id_2c9c28_idx'), models.Index(fields=['rule_triggered'], name='ai_engine_a_rule_tr_74da56_idx'), models.Index(fields=['severity'], name='ai_engine_a_severit_3146d1_idx')],
            },
        ),
    ]
